
use std::f32::consts::{FRAC_PI_2, PI};

pub const GAMEPLANESIZEX: f32 = 30.;
pub const GAMEPLANESIZEY: f32 = 10.;

pub const INITIALCARMODELROTATION: f32 = FRAC_PI_2;

// TODO: Make it different for different cars and obstacles
pub const AIRFRICTIONCOEFFICIENT: f32 = 0.1;
pub const MINIMALVELOCITYFORAIRFRICTION: f32 = 0.1;

pub const WHEELFRICTIONNORMAL: f32 = 0.3;
pub const WHEELFRICTIONSOAPED: f32 = 0.1;
pub const WHEELFRICTIONNAILED: f32 = 0.5;
pub const WHEELFRICTIONSOAPEDANDNAILED: f32 = 0.2;
pub const CARBODYFRICTION: f32 = 0.8;

pub const MAXIMALYAXISANGLEOFFSETFORTORQUECORRECTION: f32 = PI / 180. * 10.; // In rad
pub const MINIMALANGLEOFFSETFORTORQUECORRECTION: f32 = PI / 180. * 1.; // In rad
pub const MAXIMALANGULARVELOCITYFORTORQUECORRECTION: f32 = 2. * PI * 0.1; // In rad per sec
